"""user model update

Revision ID: 7e6d9c0b597d
Revises: 45ce05b2a7e1
Create Date: 2026-05-19 14:51:20.318597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e6d9c0b597d'
down_revision: Union[str, Sequence[str], None] = '45ce05b2a7e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'quantity')
    # ### end Alembic commands ###
