"""user model update

Revision ID: ab9ade550ef6
Revises: 270fa88d36a5
Create Date: 2026-05-21 04:27:16.806842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9ade550ef6'
down_revision: Union[str, Sequence[str], None] = '270fa88d36a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_slug'), table_name='books')
    op.drop_column('books', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_books_slug'), 'books', ['slug'], unique=True)
    # ### end Alembic commands ###
