"""user model update

Revision ID: d18952189f25
Revises: 7e6d9c0b597d
Create Date: 2026-05-21 01:59:14.375388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd18952189f25'
down_revision: Union[str, Sequence[str], None] = '7e6d9c0b597d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
